version: 1

# update_schedule: live is only supported on javascript, ruby:bundler, python, php:composer, dotnet:nuget, rust:cargo, elixir:hex

update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"

  - package_manager: "dotnet:nuget"
    directory: "/tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"

  - package_manager: "dotnet:nuget"
    directory: "/tools/packaging/projects/reference/System.Management.Automation"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"

  - package_manager: "dotnet:nuget"
    directory: "/test/tools/Modules"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"

  - package_manager: "dotnet:nuget"
    directory: "/src/Modules"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"

  - package_manager: "javascript"
    directory: "/test/common/markdown"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"

# scans for vNext stable
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    target_branch: "release/v6.2.2"

  - package_manager: "dotnet:nuget"
    directory: "/tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    target_branch: "release/v6.2.2"

  - package_manager: "dotnet:nuget"
    directory: "/tools/packaging/projects/reference/System.Management.Automation"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    target_branch: "release/v6.2.2"

  - package_manager: "dotnet:nuget"
    directory: "/test/tools/Modules"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    target_branch: "release/v6.2.2"

  - package_manager: "dotnet:nuget"
    directory: "/src/Modules"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    target_branch: "release/v6.2.2"

  - package_manager: "javascript"
    directory: "/test/common/markdown"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    target_branch: "release/v6.2.2"

# scans for vNext servicing
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    target_branch: "release/v6.1.5"

  - package_manager: "dotnet:nuget"
    directory: "/tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    target_branch: "release/v6.1.5"

  - package_manager: "dotnet:nuget"
    directory: "/tools/packaging/projects/reference/System.Management.Automation"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    target_branch: "release/v6.1.5"

  - package_manager: "dotnet:nuget"
    directory: "/test/tools/Modules"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    target_branch: "release/v6.1.5"

  - package_manager: "dotnet:nuget"
    directory: "/src/Modules"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    target_branch: "release/v6.1.5"

  - package_manager: "javascript"
    directory: "/test/common/markdown"
    update_schedule: "live"
    default_labels:
      - "CL-BuildPackaging"
    target_branch: "release/v6.1.5"
